import { chromium } from "playwright-core";
import { globSync } from "node:fs";
const exe = globSync("/opt/pw-browsers/chromium-*/chrome-linux/chrome")[0];
const browser = await chromium.launch({ executablePath: exe, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2 });
await page.goto("http://127.0.0.1:3000/", { waitUntil: "domcontentloaded" });
await page.waitForSelector("#theia-app-shell", { timeout: 120000 });
await page.waitForTimeout(6000);
await page.keyboard.press("Control+Shift+P");
await page.waitForSelector(".quick-input-box input", { timeout: 20000 });
await (await page.$(".quick-input-box input")).click();
await page.keyboard.type("Build and Run Swift", { delay: 50 });
await page.waitForTimeout(2000);
await page.keyboard.press("Enter");
await page.waitForFunction(() => (document.body.innerText || "").includes("Program exited"), null, { timeout: 800000 });
const body = (await page.textContent("body")).replace(/\s+/g, " ");
const i = body.indexOf("Compiling");
console.log("IDE_OUTPUT:", JSON.stringify(body.slice(i, i + 300)));
await page.screenshot({ path: "/tmp/theia-print.png", fullPage: false });
await browser.close();
